from __future__ import annotations

from typing import Any


DEMO_COMPANY: dict[str, Any] = {
    "company_code": "DEMO001",
    "company_name": "株式会社サンプルワークス",
    "legal_company_name": "株式会社サンプルワークス",
    "municipality": "デモ市",
    "fiscal_year": "令和8年度",
    "region": "千葉県",
    "business_type": "デモ事業",
    "health_insurance_branch": "千葉県",
    "employment_insurance_type": "建設の事業",
    "closing_day": "末日",
    "payment_day": 10,
    "payment_timing": "翌月",
    "provider": "OpenAI Build Week Demo",
    "customer_label_provider": "Fictional Demo",
}


DEMO_EMPLOYEES: dict[str, dict[str, Any]] = {
    "山田太郎": {
        "employee_id": "000101",
        "name": "山田太郎",
        "display_name": "山 田　太 郎",
        "municipality_code": "DEMO-CITY",
        "municipality_name": "デモ市",
        "resident_tax_collection_type": "特別徴収",
        "resident_tax_special_collection_from": "2026-06",
        "resident_tax_special_collection_to": "2027-05",
        "role": "役員",
        "birthday": "1980-01-15",
        "birthday_jp": "昭和55年1月15日",
        "tax_class": "甲欄",
        "dependents": 1,
        "base_salary": 0,
        "executive_compensation": 320000,
        "basic_salary": 0,
        "site_allowance": 0,
        "attendance_allowance": 0,
        "holiday_work_allowance": 0,
        "night_allowance": 0,
        "half_night_allowance": 0,
        "fixed_salary": 320000,
        "variable_allowance_enabled": False,
        "allowance_input_enabled": False,
        "standard_monthly_health": 320000,
        "standard_monthly_pension": 320000,
        "assessment_base": 320000,
        "social_insurance": True,
        "health_insurance": True,
        "pension_insurance": True,
        "employment_insurance": False,
        "employment_insurance_type": "建設の事業",
        "dependent_switch": [],
    },
    "佐藤花子": {
        "employee_id": "000102",
        "name": "佐藤花子",
        "display_name": "佐 藤　花 子",
        "municipality_code": "DEMO-CITY",
        "municipality_name": "デモ市",
        "resident_tax_collection_type": "特別徴収",
        "resident_tax_special_collection_from": "2026-06",
        "resident_tax_special_collection_to": "2027-05",
        "role": "社員",
        "birthday": "1992-04-10",
        "birthday_jp": "平成4年4月10日",
        "tax_class": "甲欄",
        "dependents": 0,
        "base_salary": 210000,
        "executive_compensation": 0,
        "basic_salary": 210000,
        "site_allowance": 0,
        "attendance_allowance": 0,
        "holiday_work_allowance": 0,
        "night_allowance": 0,
        "half_night_allowance": 0,
        "fixed_salary": 210000,
        "variable_allowance_enabled": False,
        "allowance_input_enabled": False,
        "standard_monthly_health": 210000,
        "standard_monthly_pension": 210000,
        "assessment_base": 210000,
        "social_insurance": True,
        "health_insurance": True,
        "pension_insurance": True,
        "employment_insurance": True,
        "employment_insurance_type": "建設の事業",
        "dependent_switch": [],
    },
}


DEMO_RESIDENT_TAX: dict[str, dict[str, Any]] = {
    "山田太郎": {
        "annual_amount": 24000,
        "monthly_amounts": {
            "6月分": 2000, "7月分": 2000, "8月分": 2000, "9月分": 2000,
            "10月分": 2000, "11月分": 2000, "12月分": 2000,
            "翌年1月分": 2000, "翌年2月分": 2000, "翌年3月分": 2000,
            "翌年4月分": 2000, "翌年5月分": 2000,
        },
    },
    "佐藤花子": {
        "annual_amount": 85000,
        "monthly_amounts": {
            "6月分": 8000, "7月分": 7000, "8月分": 7000, "9月分": 7000,
            "10月分": 7000, "11月分": 7000, "12月分": 7000,
            "翌年1月分": 7000, "翌年2月分": 7000, "翌年3月分": 7000,
            "翌年4月分": 7000, "翌年5月分": 7000,
        },
    },
}
